CREATE DATABASE pjerj;

USE pjerj;

CREATE TABLE TIPO_USUARIO (
    ID_TIPOUSUARIO INT AUTO_INCREMENT PRIMARY KEY,
    ORIGEM CHAR(1) NOT NULL,
    DESCR VARCHAR(20) NOT NULL
);

ALTER TABLE TIPO_USUARIO
ADD CONSTRAINT UC_ORIGEM UNIQUE (ORIGEM);

CREATE TABLE USUARIO (
    ID_USU INT AUTO_INCREMENT PRIMARY KEY,
    NOME_USU VARCHAR(100) NOT NULL,
    MATR_USU VARCHAR(15) NOT NULL,
    DATA_NASC DATE NOT NULL,
    EMAIL VARCHAR(100) NOT NULL,
    ID_TIPOUSUARIO INT not NULL
);

ALTER TABLE USUARIO
ADD CONSTRAINT UC_MATR_USU UNIQUE (MATR_USU);

ALTER TABLE USUARIO
ADD CONSTRAINT UC_EMAIL UNIQUE (EMAIL);

ALTER TABLE USUARIO
ADD CONSTRAINT FK_ORIGEM_TIPO_USUARIO FOREIGN KEY (ID_TIPOUSUARIO)
REFERENCES TIPO_USUARIO (ID_TIPOUSUARIO);

DELIMITER $$

CREATE or REPLACE PROCEDURE ListarUsuariosPorOrigem(IN p_origem CHAR(1))
BEGIN
    SELECT U.ID_USU, U.NOME_USU, U.MATR_USU, U.DATA_NASC, U.EMAIL, TU.ID_TIPOUSUARIO, TU.ORIGEM, TU.DESCR
    FROM USUARIO U
    inner join TIPO_USUARIO TU on U.ID_TIPOUSUARIO = TU.ID_TIPOUSUARIO
    WHERE TU.ORIGEM = p_origem;
END $$

DELIMITER ;

START TRANSACTION;

INSERT INTO pjerj.tipo_usuario (ORIGEM, DESCR)
VALUES('M', 'Magistrado'),
('F', 'Funcionário'),
('T', 'Terceirizado'),
('A', 'Aposentado'),
('P', 'Pensionista'),
('C', 'Cotista'),
('E', 'Externo');

INSERT INTO pjerj.usuario
(NOME_USU, MATR_USU, DATA_NASC, EMAIL, ID_TIPOUSUARIO)
VALUES('VIVIANE GOES DELZI', 'RJ162042', '2025-01-13', 'testenegocio@hotmail.com', 7),
('SABINE SYLVIA SCHMITT', 'RJ179264', '2025-01-13', 'teste@teste.com.br', 7),
('ALEXANDRE MARQUES PAULA', '30435', '2025-02-01', 'teste@tjrj.jus.br', 2),
('FERNANDO LUIZ DE ABREU NETTO', '6716', '2025-02-03', 'teste@tjrj.jus', 4),
('CLAUDIA MARIA MENEZES SOARES', '8041', '2025-01-13', 'teste@testando2.com.br', 4),
('PAULO DA SILVA XAVIER', 'RJ144977', '2014-09-14', 'paulodasilvaxavierteste@uol.com.br', 7),
('PAULA CRISTINA VASCONCELOS CAVALCANTE', 'RJ176594', '2019-11-17', 'adv.paulacavalcante_teste@yahoo.com.br', 7),
('JOSE PIMENTEL JUNIOR', '24789649791', '2025-01-13', 'teste1@teste.com.br', 5),
('TESTE - PREPOSTO FEBRABAN', '000123', '2016-06-02', 'teste2@teste.com.br', 7);

COMMIT;